services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.free.acme.tlschallenge=true"
      - "--certificatesresolvers.free.acme.email=postmaster@example.com"
      - "--certificatesresolvers.free.acme.storage=/acme/acme.json"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-acme:/acme
  grafana:
    image: grafana/grafana:latest
    env_file:
      - grafana.env
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - monitoring
    labels:
        - "traefik.enable=false"
        - "traefik.http.routers.grafana.rule=Host(`example.com`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls=true"
        - "traefik.http.routers.grafana.tls.certresolver=free"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
  influxdb:
    container_name: influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=mtrgraphs
      - DOCKER_INFLUXDB_INIT_PASSWORD=mtrgraphs
      - DOCKER_INFLUXDB_INIT_ORG=mtrgraphs
      - DOCKER_INFLUXDB_INIT_BUCKET=mtrgraphs
      - DOCKER_INFLUXDB_INIT_RETENTION=4w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
      - INFLUXDB_HTTP_LOG_ENABLED=true
    image: influxdb:2
    networks:
      - monitoring
  goservice:
    image: adamgordon/mtrgraphs
    depends_on:
      - influxdb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=mtrgraphs
      - INFLUXDB_BUCKET=mtrgraphs
    networks:
      - monitoring
    command:
      - "172.24.0.30/24"
networks:
  monitoring:
volumes:
  grafana:
  influxdb-data:
  influxdb-config:
  traefik-acme:
